lb:
  build: .
  links:
  - consul
  ports:
  - "80:80"

consul:
  command: -bootstrap -advertise 10.0.2.15 -recursor 8.8.8.8 -node myconsul
  image: gliderlabs/consul-server:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
