lb:
  build: ./lb
  links:
  - consul
  ports:
  - "80:80"

consul:
  command: -bootstrap -advertise 10.0.2.15 -recursor 8.8.8.8 -node myconsul
  image: gliderlabs/consul-server:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"

telegraf:
  build: ./telegraf
  links: 
  - lb
  - influx

influx:
  image: tutum/influxdb
  ports: 
  - "8083:8083"
  - "8086:8086"

grafana:
  image: grafana/grafana
  environment:
      GF_DATABASE_PATH: /gfdb/grafana.db
  links: 
      - influx
  ports: 
      - "3000:3000"
  volumes:
      - ~/grafana:/gfdb